### ISSUE TITLE
Elemente multivisit metrisch

### ISSUE THREAD

**Issue by wadepuhlm** [rietzlers/followr#1]
Bitte folgende Adten und Anordung
N Nmisssing   Mean+- Standarddeviation      Median [2.Quartile - 4 Quartile]  Range [Min, Max]

**Comment by rietzlers** [comment]
Hallo Martin, mache ich.

**Comment by rietzlers** [comment]
sollte jetzt so sein

**Comment by wadepuhlm** [comment]
ja passt soweit. kleiner design-optimierung siehe issue #10
