### ISSUE TITLE
EQ Life quality daten

### ISSUE THREAD

**Issue by wadepuhlm** [rietzlers/followr#12]
Lieber Stephan, die Life quality daten (Datei EQ) tauchen nicht auf, vermutlich wegen der Umstellung von "factor" (=nominal ) auf interger. Wollte die Tabellen gerade einbauen.

**Comment by rietzlers** [comment]
Kategorielle Variablen sollen einheitlich kodiert exportiert werden! Also auch alle EQ-Daten. Wenn du kategorielle Daten anhand ihres numerischen Codes (also als metrische Variablen) berichten willst geht das über die "report_type" option in der Funktion 
report_visits.

D.h. medpass soll diese Daten bitte wieder kodiert exportieren.

**Comment by wadepuhlm** [comment]
NVT angeschrieben, Metrische Auswertung läuft

**Comment by wadepuhlm** [comment]
Nur Zur Dokumentation, weil das über Email lief: Faiss bittet es bei numerisch zu belassen. Fargabogendaten sind ein Sonderfall, weil immer numerisch auszuwerten. Tipp Sie sind auf Deinen Standard leicht runterzubrechen, indem pro Patienten und Visit und Score-Dimension ein Wert errechent wird.
Damit ist das Issue auch geschlossen
