### ISSUE TITLE
Medical History

### ISSUE THREAD

**Issue by rietzlers** [rietzlers/followr#15]
die medical-history daten sind im Datensatz  `mh` im standardformat gespeichert.
Damit kannst du diese Daten mit standard-funktions berichten.

**Comment by wadepuhlm** [comment]
Irgendwas geht noch schief: 
report_population(mh,c(
  mitral_valve_insufficiency, 
  mitral_valve_stenosis,
  tricuspid_valve_disease),
  caption = 'Valve diagnosis')
Führt zu Fehlermeldung: Fehler in (1 - h) * qs[i] : nicht-numerisches Argument für binären Operator

**Comment by wadepuhlm** [comment]
Da die neuen Variablen nicht im Metadaten-File stehen, aber der ursprüngliche File auch nicht mehr vorhanden ist, suche ich nach einer Möglichkeit die Variablennamen zu kopieren, was das Programmieren extrem verienfachen würde. Maches es mal aus dem Excel als work-around

**Comment by wadepuhlm** [comment]
Habe mh-Auswertung eingebaut (committed und pushed!)
Die anzeige der Variablen funktionierte nicht, habe sie reingehackt, damit das vom Tisch ist, war auch nicht schlimm.

**Comment by wadepuhlm** [comment]
Da sind von medpas noch Fehler in den Bezeichnungen:
- "atrial fibrilation and futter" muss heißen " ...flutter>"
- "chronic obstructive pulonary disease, copd" muss heißen "... pulmonary ..."
Vermutlich ist es besser, wenn Du das in der Datenaufbereitung korrigierst. Hatte ich auch so gemacht.

**Comment by rietzlers** [comment]
Diese Tippfehler korrigiere ich erstmal nicht. Das soll medpass machen oder wir lassen das als Schönheitsfehler stehen. 
Lass uns das aber mal zurückstellen. Und erst das wesentliche gerade ziehen, nämlich die Formate/Kategorien der 
Variablen:

Ich habe die die Variablen im Datensatz mh nun mit einem format "grade" versehen so das du sie nun mit der Standardfunktion report_population berichten kannst. Allerdings ist das Problem, das die dabei erzeugten Variablen zum Teil unterschiedliche Kategoreien haben. Und nicht alle die gleichen wie sie eigentlich müssten. Das ist jetzt nicht zu ändern.

Die möglichen Ausprägungen der jeweiligen Variable erezuge ich on-the-fly. D.h. es werden nur die Auspräungen berichtet, die auch vorkommen. Das geht nicht anders, da für diese Variablen ja kein Format definiert ist.

Da muß du schauen das du nur die Variablen in einer Tabelle berichtest die auch gleich Ausprägungen haben.

Ebenso sind zum Teil immer noch komische Eintragungen vorhanden, z.B. ".", "A" usw.. Das ist auch ein Problem von medpass.

**Comment by wadepuhlm** [comment]
Lieber Stephan,

 

dann schrieb ich die Details an NVT.

 

Den Abschnitt zur MH habe ich erst mal auskommentiert. Es macht meiner Ansicht nach nichts, wenn bei einer Variable die Ausprägungen in Spalte 1-3 stehen und 4-7 leer sind und bei der nächsten die Spalten 1-3- leer und dafür die Spalten 4-7 gefüllt sind. Solange das Deine Funktion packt?!

 

Wir sollten heute telefonieren, um

*        Deine neueste Version runterzuholen (ach das geht ja automatisch, ich probiere es gleich)

*        Zu überlegen, wann wir Herrn Faiss den ersten Bericht vorstellen, morgen oder erst nächste Woche: Ich plädiere für nächste Woche.

 

Bis vermutlich heute Nachmittag?

Liebe Grüße

Martin

 

Dr. Martin Wadepuhl

Büro für Versuchsplanung und statistische Auswertung VSA

Am Heidehof 54

D-14163 Berlin

 

T: 030-80586166 Berlin

T: 0731-9386707 Ulm

H: 0151-70820945

E: wadepuhl.m.vsa@t-online.de

 

Von: Stephan Rietzler [mailto:notifications@github.com] 
Gesendet: Donnerstag, 30. Juli 2020 10:26
An: rietzlers/followr <followr@noreply.github.com>
Cc: wadepuhlm <wadepuhl.m.vsa@t-online.de>; Assign <assign@noreply.github.com>
Betreff: Re: [rietzlers/followr] Medical History (#15)

 

Diese Tippfehler korrigiere ich erstmal nicht. Das soll medpass machen oder wir lassen das als Schönheitsfehler stehen.
Lass uns das aber mal zurückstellen. Und erst das wesentliche gerade ziehen, nämlich die Formate/Kategorien der
Variablen:

Ich habe die die Variablen im Datensatz mh nun mit einem format "grade" versehen so das du sie nun mit der Standardfunktion report_population berichten kannst. Allerdings ist das Problem, das die dabei erzeugten Variablen zum Teil unterschiedliche Kategoreien haben. Und nicht alle die gleichen wie sie eigentlich müssten. Das ist jetzt nicht zu ändern.

Die möglichen Ausprägungen der jeweiligen Variable erezuge ich on-the-fly. D.h. es werden nur die Auspräungen berichtet, die auch vorkommen. Das geht nicht anders, da für diese Variablen ja kein Format definiert ist.

Da muß du schauen das du nur die Variablen in einer Tabelle berichtest die auch gleich Ausprägungen haben.

Ebenso sind zum Teil immer noch komische Eintragungen vorhanden, z.B. ".", "A" usw.. Das ist auch ein Problem von medpass.

**Comment by rietzlers** [comment]
Habe die NA-Kodierungen von mepass jetzt doch in meine NA-Kodierung übernommen. medpass muß jetzt nur noch schauen das alle eintragungen korrekt sind. Momentan gibt es noch zumindest noch "N" und "." in der Spalte grade die da nicht hingehören.

**Comment by wadepuhlm** [comment]
Asuwertung steht bis auf die die Ungereimtheiten der Daten. Diese ist weitergegeben. Also schließen
