### ISSUE TITLE
Konvention Variablennamen

### ISSUE THREAD

**Issue by wadepuhlm** [rietzlers/followr#17]
Achtung Inkonsistenz: Es gibt klein geschriebene Variablen sieh CO.visit. Hast du das bedacht?

**Comment by rietzlers** [comment]
diese variable ist von mir: Grund in den excel-sheets ist diese variable nicht einheitlich benannt. deswegen habe ich sie für alle datensätzte mit diesem namen standardisiert;  ist also keine inkonsistenz
