### ISSUE TITLE
Kategorielle EQ-Variablen als numerische Variablen importieren

### ISSUE THREAD

**Issue by rietzlers** [rietzlers/followr#18]
Ich setze dann die Format-Namen der entsprechenden Variablen im datensatz variable_meta_info auf NA. Damit
werden sie dann beim import auch als numerisch und nicht als faktor im Datensatz EQ angelegt. Auswertung ist dann 
NUR noch metrisch möglich.

**Comment by wadepuhlm** [comment]
Vermutlich gibt es da noch Probleme wegen des HinunderHers, sorry:
 filter(EQ, visit == 'Baseline') %>% report_population(c(EQMO, EQSC, EQUA, EQPD, EQAD), caption = 'EQol5 at baseline')

Verstehe aber dennoch diese Fehlermeldung nicht:
Fehler in report_population.factors(data, { : Variables have different formats/categories! Can not report them in one table!

**Comment by rietzlers** [comment]
Ist jetzt alles numerisch.
