### ISSUE TITLE
AE-Daten

### ISSUE THREAD

**Issue by rietzlers** [rietzlers/followr#22]
Zur Bedeutung der Variablen im Datensatz AE:

- AENUM: Dies ist lediglich ein Schlüssel für das AE. Die Reihenfolge ist willkürlich und hat nichts mit dem
AE-Start-Datum zu tun.
 
- AENOFU: character-Variable die die Follow-up- "Aktivitäten" zu einem AE dokumentiert. D.h. der 'initial report' müsste
hier immer ein 'A' stehen haben. Dann wird für jeden follow-up report 'hochgezält'. Der final report zum AE hat den höchsten Buchstaben. Das ist zumindest mein Verständnis! Bitte um Klärung! 
**Unstimmigkeiten:** :-1: 

  - Bei z.B. Patient 112002 gibt es aber einen Eintrag im Datensatz AE (AENUM = 1, major-bleeding) bei dem es einen Final report gibt, aber keinen initial report

  - Bei Patient 120007 gibt es einen Eintrag bei dem eine '4' in AENOFU steht. Passt auch nicht! 

  - Insgesamt passt AENOFU nicht zu AEKR. Zumindest nicht nach meinem Verständnis.

- Bei AEs der Kategorie "other" ist kommt es oft vor das meherer AEs dieser Kategorie mit gleichem Startdatum dokumentiert sind. 

- category_repeat_nr : Zählt die dokumentierten AEs einer Kategory pro Patient hoch. Die Reihenfolge wird über das AE-Start Datum besimmt! Dies funktioniert bei allen Kategorien außer der Kategorie "Other".  In dieser Kategorie das mehrere AEs mit gleichem Start-Datum dokumentiert sind.

**Comment by wadepuhlm** [comment]
Dass mehrere AEs mit gleichen Datum vorkommen kann ist logisch: Die Guidelines verlangen für jede Diagnose einen extra Datensatz. 
Den Rest zusammentragen und auch bei der Programmierung NICHT beachten, da die Datensätze zum großen Teil noch geminitoriert sind. 
Also einfach nach SChem F vorgehen, ohne Sonderregelungen!!!

**Comment by rietzlers** [comment]
Gut. Für die Frage nach der Report-Nummerierung, die jetzt hier noch offen ist habe ich ein extra issue #34 angelegt.
