### ISSUE TITLE
Unstimmige Patienten-Zahlen in Klinik 121 und 201

### ISSUE THREAD

**Issue by rietzlers** [rietzlers/followr#23]
Bei den Zentren 121 und 201 gibt es unstimmigkeiten:

- 121 hat beim baseline 9 Patienten aufgenommen, es werden aber nur 8 operiert. (121008 hat kein Procedure-Datum!, 121009 verschwindet 3 Tage nach der OP am 03.07.2020. Er sollte aber zu diesem Zeitpunkt den 30-Tage-Visit absolviert haben!) 

- 201 operiert 29 Patienten, hat im Baseline aber nur 28 erfasst (Written consent liegt auch nur für 28 Patienten vor) Für den Patienten 201034 gibt es keinen Eintrag im Datensatz BA! D.h. es liegt kein Written consent vor bzw. ist nicht dokumentiert! Er wurde aber operiert!

Auffällig ist, das im Center 201 die Patienten fortlaufend von 1 bis 28 durchnummeriert werden, und dann plötzlich ein Patient mit
der Nummer 34 auftaucht! Wo sind die Patienten 29-33? In diesem Center sind auch die Hälfte aller Patienten in der Studie operiert! Auch auffällig. 

Für Patient 2010034 fehlt auch der Baseline-Datensatz.

**Comment by wadepuhlm** [comment]
In E-Mail an MF erwähnt

**Comment by rietzlers** [comment]
transfer to issue #39
