### ISSUE TITLE
Written consent fehlt!

### ISSUE THREAD

**Issue by rietzlers** [rietzlers/followr#25]
Die beiden Datensätze mit Information über den Eingriff haben 61 Einträge! Dies dürfte nicht sein, da der Baseline datensatze BA
nur 60 Einträge (Patienten ) hat! 

Im Baseline-Datensatz sind aber nur 60 Einträge vorhanden. Es fehlt also ein Written Consent. Oder es stimmt etwas nicht mit der Patienten ID (SUBJID). 

Der fehlende Patient im Datensatz Baseline ist 201034. Siehe auch Issue #23

**Comment by wadepuhlm** [comment]
In E-Mail an MF angesprochen

**Comment by rietzlers** [comment]
aufgenommen in issue #39
