### ISSUE TITLE
Patient 121008 hat kein OP-Datum

### ISSUE THREAD

**Issue by rietzlers** [rietzlers/followr#26]
Bei diesem Patienten fehlt das Datum der Index-Procedure! Die Bioprosthesis wurde allerdings laut Datensatz PR
implantiert!  Für diesen Patienten gibt es aber einen Discharge und 30 days FU Eintrag. Außerdem wurde ein AE dokumentiert.

**Comment by wadepuhlm** [comment]
In E-Mail an MF angesprochen

**Comment by rietzlers** [comment]
Wird in issue #39 erwähnt
