### ISSUE TITLE
Device Deficiency

### ISSUE THREAD

**Issue by rietzlers** [rietzlers/followr#30]
Device Deviciency Daten in event_profiles aufnehmen. Das relevante Datum ist DDDADIS (Date of discovering)
Ein Device-Deficiency Event ist eindeutig über SUBJID und DDNO identifizierbar. (@wadepuhlm Bitte klären ob das stimmt)

**Comment by rietzlers** [comment]
device-deficiencies sind nun in event_profiles aufgenommen.

**Comment by wadepuhlm** [comment]
Ja, muss so sein. Wir machen da erst mal nur ein Lisiting daraus. Ich werde es einbauen.
