### ISSUE TITLE
AE-Report

### ISSUE THREAD

**Issue by rietzlers** [rietzlers/followr#35]
Ich habe jetzt eine Funktion erstellt, die zwei Tabellen erzeugt: 

1. Cross-Classification aller dokumentierten AEs nach Categorie und Primary Cause.
2. Summary-Statistic für die Wahrscheinlichkeit  mit der ein Patient mindestens ein  AE einer bestimmten Kategorie bis zum Zeitpunkt des Reports (bzw. bis zu einem definierten Studienzeitpunkt) hat. 

Usage: `ae_custom %>% report_aes()`

Als Referenzpopulation für diese geschätzte Eintritts-Wahrscheinlichkeit für ein AE habe ich die ITT-Population (Vorläufig auf Size = 60 gesetzt) genommen. Wie besprochen sollte man diese Schätzung aber mit Vorsicht genießen. Gibt es Studienabbrecher oder Todesfälle so wird die Wahrscheinlichkeit für das Auftreten eines AEs systematisch auf diese Weise systematisch unterschätzt.

**Comment by wadepuhlm** [comment]
Grobe Übersicht: Ist Okay so
