### ISSUE TITLE
 pre-op and post-op - "visits" für pullback  

### ISSUE THREAD

**Issue by wadepuhlm** [rietzlers/followr#7]
Die werte "pullback" sollten als multi-visit (pre-op und post-op) breichtet werden. Momentan
stehen sie als zwei variablen im Datensatz PR.
PR.PRPRNIAV =  Wert (pullback measurement) vor der Prozedur
PR.PROINAV   = Wert nach der Prozedur

**Comment by rietzlers** [comment]
Ich werde einen Datensatz erzeugen in dem diese Werte in einer Variablen stehen und eine Zusatzvariable "visit" einführen in der die entsprechenden visits "Pre-Procedure" und "Post-Procedure" stehen.
Dann kannst du diese Variable wie üblich als multi-visit berichten.

**Comment by rietzlers** [comment]
es gibt nun einen datensatz pr_av_max in dem diese Daten vorhanden sind.
Den report kannst du mit folgender Codezeilen erzeugen:

`pr_av_max %>% report_visit_values(av_max, test = list(baseline = "pre-procedure"))`

Beachte das du hier den 'baseline'-visit explizit angeben mußt, da der default baseline-visit 'Baseline'
in diesem daten-satz nicht vorkommt.
