### ISSUE TITLE
Kombination der LOT Nummern

### ISSUE THREAD

**Issue by wadepuhlm** [rietzlers/followr#8]
erzeuge variablen:
- IE.IEDELLOT: Alle werte aus den variablen IE.IENDLOT1 - 6 sollen mit Komma getrennt hier stehen. (patient-wise)- -
- IE.IEVALLOT: Alle werte aus den variablen IE.IENPSE11 - 6 sollen mit Komma getrennt hier stehen. (patient-wise)

**Comment by rietzlers** [comment]
Um welche Variablen in welchem Datensatz geht es?

**Comment by wadepuhlm** [comment]
IE

**Comment by wadepuhlm** [comment]
hHabe mit „IE“ geantwortet weiß nicht ob es ankam

 

 

 

Dr. Martin Wadepuhl

Büro für Versuchsplanung und statistische Auswertung VSA

Am Heidehof 54

D-14163 Berlin

 

T: 030-80586166 Berlin

T: 0731-9386707 Ulm

H: 0151-70820945

E: wadepuhl.m.vsa@t-online.de

 

Von: Stephan Rietzler [mailto:notifications@github.com] 
Gesendet: Mittwoch, 22. Juli 2020 16:38
An: rietzlers/followr <followr@noreply.github.com>
Cc: wadepuhlm <wadepuhl.m.vsa@t-online.de>; Assign <assign@noreply.github.com>
Betreff: Re: [rietzlers/followr] Variablenkombination 2. Fall (#8)

 

Um welche Variablen in welchem Datensatz geht es?

**Comment by rietzlers** [comment]
Die variablen sind nun im Datensatz IE vorhanden. Allerdings mit leicht anderem Namen als von dir vorgeschlagen,
nämlich: iendlots und ienpses
Begründung: Per Konvention werde ich alle Variablen die nicht aus den excel-sheets kommen mit kleinbuchstaben 
bezeichnen.

**Comment by wadepuhlm** [comment]
Alles gut schließen wir das ab: Ist im Tabellenteil verarbeitet
